name: outdoor_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  google_fonts: ^6.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  go_router: ^13.1.0
  http: ^1.3.0
  supabase_flutter: ^2.3.2
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  flutter_animate: ^4.5.0
  uuid: ^4.3.3
  fl_chart: ^0.66.0
  flutter_dotenv: ^5.1.0
  geolocator: ^13.0.4
  geocoding: ^3.0.0
  numberpicker: ^2.1.2
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/fonts/ 